gdays <- read.csv('/Volumes/group_dv/personal/DValenzano/Sep2014/qtl-direction-analysis/ReAutoReqtlresults/gdays2_tab.csv', sep=',', header=TRUE)
gdaysM <- read.csv('/Volumes/group_dv/personal/DValenzano/Sep2014/qtl-direction-analysis/ReAutoReqtlresults/gdaysM2_tab.csv', sep=',', header=TRUE)
gdaysF <- read.csv('/Volumes/group_dv/personal/DValenzano/Sep2014/qtl-direction-analysis/ReAutoReqtlresults/gdaysF2_tab.csv', sep=',', header=TRUE)


# First, I start with gdays

gdays_LG1 <- subset(gdays, gdays$LG == '1')
gdays_LG2 <- subset(gdays, gdays$LG == '2')
gdays_LG3 <- subset(gdays, gdays$LG == '3')
gdays_LG4 <- subset(gdays, gdays$LG == '4')
gdays_LG5 <- subset(gdays, gdays$LG == '5')
gdays_LG6 <- subset(gdays, gdays$LG == '6')
gdays_LG7 <- subset(gdays, gdays$LG == '7')
gdays_LG8 <- subset(gdays, gdays$LG == '8')
gdays_LG9 <- subset(gdays, gdays$LG == '9')
gdays_LG10 <- subset(gdays, gdays$LG == '10')
gdays_LG11 <- subset(gdays, gdays$LG == '11')
gdays_LG12 <- subset(gdays, gdays$LG == '12')
gdays_LG13 <- subset(gdays, gdays$LG == '13')
gdays_LG14 <- subset(gdays, gdays$LG == '14')
gdays_LG15 <- subset(gdays, gdays$LG == '15')
gdays_LG16 <- subset(gdays, gdays$LG == '16')
gdays_LG17 <- subset(gdays, gdays$LG == '17')
gdays_LG18 <- subset(gdays, gdays$LG == '18')
gdays_LG19 <- subset(gdays, gdays$LG == '19')

### LG 1:4
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdays_LG1$cM, gdays_LG1$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG1", xlim=c(0,max(gdays_LG1$cM)))
plot(gdays_LG2$cM, gdays_LG2$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG2", xlim=c(0,max(gdays_LG2$cM)))
plot(gdays_LG3$cM, gdays_LG3$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG3", xlim=c(0,max(gdays_LG3$cM)))
plot(gdays_LG4$cM, gdays_LG4$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG4", xlim=c(0,max(gdays_LG4$cM)))

plot(gdays_LG1$cM, gdays_LG1$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG1$cM)), ylab="days", xlab="cM", main="G cross, LG1: Surv by Gen")
par(new=TRUE)
plot(gdays_LG1$cM, gdays_LG1$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG1$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG1$cM, gdays_LG1$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG1$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG2$cM, gdays_LG2$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG2$cM)), ylab="days", xlab="cM", main="G cross, LG2: Surv by Gen")
par(new=TRUE)
plot(gdays_LG2$cM, gdays_LG2$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG2$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG2$cM, gdays_LG2$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG2$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG3$cM, gdays_LG3$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG3$cM)), ylab="days", xlab="cM", main="G cross, LG3: Surv by Gen")
par(new=TRUE)
plot(gdays_LG3$cM, gdays_LG3$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG3$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG3$cM, gdays_LG3$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG3$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG4$cM, gdays_LG4$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG4$cM)), ylab="days", xlab="cM", main="G cross, LG4: Surv by Gen")
par(new=TRUE)
plot(gdays_LG4$cM, gdays_LG4$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG4$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG4$cM, gdays_LG4$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG4$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

### LG 5:8
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdays_LG5$cM, gdays_LG5$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG5", xlim=c(0,max(gdays_LG5$cM)))
plot(gdays_LG6$cM, gdays_LG6$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG6", xlim=c(0,max(gdays_LG6$cM)))
plot(gdays_LG7$cM, gdays_LG7$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG7", xlim=c(0,max(gdays_LG7$cM)))
plot(gdays_LG8$cM, gdays_LG8$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG8", xlim=c(0,max(gdays_LG8$cM)))

plot(gdays_LG5$cM, gdays_LG5$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG5$cM)), ylab="days", xlab="cM", main="G cross, LG5: Surv by Gen")
par(new=TRUE)
plot(gdays_LG5$cM, gdays_LG5$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG5$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG5$cM, gdays_LG5$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG5$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG6$cM, gdays_LG6$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG6$cM)), ylab="days", xlab="cM", main="G cross, LG6: Surv by Gen")
par(new=TRUE)
plot(gdays_LG6$cM, gdays_LG6$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG6$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG6$cM, gdays_LG6$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG6$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG7$cM, gdays_LG7$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG7$cM)), ylab="days", xlab="cM", main="G cross, LG7: Surv by Gen")
par(new=TRUE)
plot(gdays_LG7$cM, gdays_LG7$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG7$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG7$cM, gdays_LG7$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG7$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG8$cM, gdays_LG8$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG8$cM)), ylab="days", xlab="cM", main="G cross, LG8: Surv by Gen")
par(new=TRUE)
plot(gdays_LG8$cM, gdays_LG8$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG8$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG8$cM, gdays_LG8$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG8$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")


### LG 9:12
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdays_LG9$cM, gdays_LG9$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG9", xlim=c(0,max(gdays_LG9$cM)))
plot(gdays_LG10$cM, gdays_LG10$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG10", xlim=c(0,max(gdays_LG10$cM)))
plot(gdays_LG11$cM, gdays_LG11$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG11", xlim=c(0,max(gdays_LG11$cM)))
plot(gdays_LG12$cM, gdays_LG12$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG12", xlim=c(0,max(gdays_LG12$cM)))

plot(gdays_LG9$cM, gdays_LG9$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG9$cM)), ylab="days", xlab="cM", main="G cross, LG9: Surv by Gen")
par(new=TRUE)
plot(gdays_LG9$cM, gdays_LG9$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG9$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG9$cM, gdays_LG9$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG9$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG10$cM, gdays_LG10$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG10$cM)), ylab="days", xlab="cM", main="G cross, LG10: Surv by Gen")
par(new=TRUE)
plot(gdays_LG10$cM, gdays_LG10$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG10$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG10$cM, gdays_LG10$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG10$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG11$cM, gdays_LG11$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG11$cM)), ylab="days", xlab="cM", main="G cross, LG11: Surv by Gen")
par(new=TRUE)
plot(gdays_LG11$cM, gdays_LG11$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG11$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG11$cM, gdays_LG11$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG11$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG12$cM, gdays_LG12$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG12$cM)), ylab="days", xlab="cM", main="G cross, LG12: Surv by Gen")
par(new=TRUE)
plot(gdays_LG12$cM, gdays_LG12$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG12$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG12$cM, gdays_LG12$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG12$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

###LG 13 to 16
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdays_LG13$cM, gdays_LG13$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG13", xlim=c(0,max(gdays_LG13$cM)))
plot(gdays_LG14$cM, gdays_LG14$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG14", xlim=c(0,max(gdays_LG14$cM)))
plot(gdays_LG15$cM, gdays_LG15$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG15", xlim=c(0,max(gdays_LG15$cM)))
plot(gdays_LG16$cM, gdays_LG16$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG16", xlim=c(0,max(gdays_LG16$cM)))

plot(gdays_LG13$cM, gdays_LG13$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG13$cM)), ylab="days", xlab="cM", main="G cross, LG13: Surv by Gen")
par(new=TRUE)
plot(gdays_LG13$cM, gdays_LG13$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG13$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG13$cM, gdays_LG13$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG13$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG14$cM, gdays_LG14$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG14$cM)), ylab="days", xlab="cM", main="G cross, LG14: Surv by Gen")
par(new=TRUE)
plot(gdays_LG14$cM, gdays_LG14$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG14$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG14$cM, gdays_LG14$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG14$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG15$cM, gdays_LG15$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG15$cM)), ylab="days", xlab="cM", main="G cross, LG15: Surv by Gen")
par(new=TRUE)
plot(gdays_LG15$cM, gdays_LG15$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG15$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG15$cM, gdays_LG15$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG15$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG16$cM, gdays_LG16$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG16$cM)), ylab="days", xlab="cM", main="G cross, LG16: Surv by Gen")
par(new=TRUE)
plot(gdays_LG16$cM, gdays_LG16$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG16$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG16$cM, gdays_LG16$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG16$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

###LG 17: 19
layout(matrix(c(1,2,3,4,5,6),2,3,byrow=TRUE), heights=c(1,2))
plot(gdays_LG17$cM, gdays_LG17$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG17", xlim=c(0,max(gdays_LG17$cM)))
plot(gdays_LG18$cM, gdays_LG18$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG18", xlim=c(0,max(gdays_LG18$cM)))
plot(gdays_LG19$cM, gdays_LG19$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG19", xlim=c(0,max(gdays_LG19$cM)))

plot(gdays_LG17$cM, gdays_LG17$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG17$cM)), ylab="days", xlab="cM", main="G cross, LG17: Surv by Gen")
par(new=TRUE)
plot(gdays_LG17$cM, gdays_LG17$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG17$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG17$cM, gdays_LG17$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG17$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG18$cM, gdays_LG18$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG18$cM)), ylab="days", xlab="cM", main="G cross, LG18: Surv by Gen")
par(new=TRUE)
plot(gdays_LG18$cM, gdays_LG18$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG18$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG18$cM, gdays_LG18$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG18$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdays_LG19$cM, gdays_LG19$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdays_LG19$cM)), ylab="days", xlab="cM", main="G cross, LG19: Surv by Gen")
par(new=TRUE)
plot(gdays_LG19$cM, gdays_LG19$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdays_LG19$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdays_LG19$cM, gdays_LG19$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdays_LG19$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

################BELOW WILL FOLLOW THE SAME ANALYSIS AS ABOVE, FOR GDAYSM#######################

gdaysM_LG1 <- subset(gdaysM, gdaysM$LG == '1')
gdaysM_LG2 <- subset(gdaysM, gdaysM$LG == '2')
gdaysM_LG3 <- subset(gdaysM, gdaysM$LG == '3')
gdaysM_LG4 <- subset(gdaysM, gdaysM$LG == '4')
gdaysM_LG5 <- subset(gdaysM, gdaysM$LG == '5')
gdaysM_LG6 <- subset(gdaysM, gdaysM$LG == '6')
gdaysM_LG7 <- subset(gdaysM, gdaysM$LG == '7')
gdaysM_LG8 <- subset(gdaysM, gdaysM$LG == '8')
gdaysM_LG9 <- subset(gdaysM, gdaysM$LG == '9')
gdaysM_LG10 <- subset(gdaysM, gdaysM$LG == '10')
gdaysM_LG11 <- subset(gdaysM, gdaysM$LG == '11')
gdaysM_LG12 <- subset(gdaysM, gdaysM$LG == '12')
gdaysM_LG13 <- subset(gdaysM, gdaysM$LG == '13')
gdaysM_LG14 <- subset(gdaysM, gdaysM$LG == '14')
gdaysM_LG15 <- subset(gdaysM, gdaysM$LG == '15')
gdaysM_LG16 <- subset(gdaysM, gdaysM$LG == '16')
gdaysM_LG17 <- subset(gdaysM, gdaysM$LG == '17')
gdaysM_LG18 <- subset(gdaysM, gdaysM$LG == '18')
gdaysM_LG19 <- subset(gdaysM, gdaysM$LG == '19')

### LG 1:4
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysM_LG1$cM, gdaysM_LG1$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG1", xlim=c(0,max(gdaysM_LG1$cM)))
plot(gdaysM_LG2$cM, gdaysM_LG2$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG2", xlim=c(0,max(gdaysM_LG2$cM)))
plot(gdaysM_LG3$cM, gdaysM_LG3$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG3", xlim=c(0,max(gdaysM_LG3$cM)))
plot(gdaysM_LG4$cM, gdaysM_LG4$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG4", xlim=c(0,max(gdaysM_LG4$cM)))

plot(gdaysM_LG1$cM, gdaysM_LG1$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG1$cM)), ylab="days", xlab="cM", main="G cross, LG1: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG1$cM, gdaysM_LG1$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG1$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG1$cM, gdaysM_LG1$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG1$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG2$cM, gdaysM_LG2$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG2$cM)), ylab="days", xlab="cM", main="G cross, LG2: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG2$cM, gdaysM_LG2$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG2$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG2$cM, gdaysM_LG2$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG2$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG3$cM, gdaysM_LG3$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG3$cM)), ylab="days", xlab="cM", main="G cross, LG3: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG3$cM, gdaysM_LG3$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG3$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG3$cM, gdaysM_LG3$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG3$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG4$cM, gdaysM_LG4$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG4$cM)), ylab="days", xlab="cM", main="G cross, LG4: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG4$cM, gdaysM_LG4$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG4$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG4$cM, gdaysM_LG4$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG4$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

### LG 5:8
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysM_LG5$cM, gdaysM_LG5$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG5", xlim=c(0,max(gdaysM_LG5$cM)))
plot(gdaysM_LG6$cM, gdaysM_LG6$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG6", xlim=c(0,max(gdaysM_LG6$cM)))
plot(gdaysM_LG7$cM, gdaysM_LG7$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG7", xlim=c(0,max(gdaysM_LG7$cM)))
plot(gdaysM_LG8$cM, gdaysM_LG8$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG8", xlim=c(0,max(gdaysM_LG8$cM)))

plot(gdaysM_LG5$cM, gdaysM_LG5$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG5$cM)), ylab="days", xlab="cM", main="G cross, LG5: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG5$cM, gdaysM_LG5$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG5$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG5$cM, gdaysM_LG5$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG5$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG6$cM, gdaysM_LG6$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG6$cM)), ylab="days", xlab="cM", main="G cross, LG6: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG6$cM, gdaysM_LG6$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG6$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG6$cM, gdaysM_LG6$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG6$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG7$cM, gdaysM_LG7$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG7$cM)), ylab="days", xlab="cM", main="G cross, LG7: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG7$cM, gdaysM_LG7$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG7$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG7$cM, gdaysM_LG7$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG7$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG8$cM, gdaysM_LG8$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG8$cM)), ylab="days", xlab="cM", main="G cross, LG8: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG8$cM, gdaysM_LG8$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG8$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG8$cM, gdaysM_LG8$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG8$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")


### LG 9:12
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysM_LG9$cM, gdaysM_LG9$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG9", xlim=c(0,max(gdaysM_LG9$cM)))
plot(gdaysM_LG10$cM, gdaysM_LG10$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG10", xlim=c(0,max(gdaysM_LG10$cM)))
plot(gdaysM_LG11$cM, gdaysM_LG11$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG11", xlim=c(0,max(gdaysM_LG11$cM)))
plot(gdaysM_LG12$cM, gdaysM_LG12$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG12", xlim=c(0,max(gdaysM_LG12$cM)))

plot(gdaysM_LG9$cM, gdaysM_LG9$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG9$cM)), ylab="days", xlab="cM", main="G cross, LG9: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG9$cM, gdaysM_LG9$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG9$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG9$cM, gdaysM_LG9$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG9$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG10$cM, gdaysM_LG10$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG10$cM)), ylab="days", xlab="cM", main="G cross, LG10: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG10$cM, gdaysM_LG10$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG10$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG10$cM, gdaysM_LG10$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG10$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG11$cM, gdaysM_LG11$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG11$cM)), ylab="days", xlab="cM", main="G cross, LG11: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG11$cM, gdaysM_LG11$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG11$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG11$cM, gdaysM_LG11$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG11$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG12$cM, gdaysM_LG12$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG12$cM)), ylab="days", xlab="cM", main="G cross, LG12: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG12$cM, gdaysM_LG12$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG12$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG12$cM, gdaysM_LG12$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG12$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

###LG 13 to 16
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysM_LG13$cM, gdaysM_LG13$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG13", xlim=c(0,max(gdaysM_LG13$cM)))
plot(gdaysM_LG14$cM, gdaysM_LG14$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG14", xlim=c(0,max(gdaysM_LG14$cM)))
plot(gdaysM_LG15$cM, gdaysM_LG15$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG15", xlim=c(0,max(gdaysM_LG15$cM)))
plot(gdaysM_LG16$cM, gdaysM_LG16$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG16", xlim=c(0,max(gdaysM_LG16$cM)))

plot(gdaysM_LG13$cM, gdaysM_LG13$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG13$cM)), ylab="days", xlab="cM", main="G cross, LG13: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG13$cM, gdaysM_LG13$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG13$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG13$cM, gdaysM_LG13$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG13$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG14$cM, gdaysM_LG14$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG14$cM)), ylab="days", xlab="cM", main="G cross, LG14: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG14$cM, gdaysM_LG14$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG14$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG14$cM, gdaysM_LG14$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG14$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG15$cM, gdaysM_LG15$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG15$cM)), ylab="days", xlab="cM", main="G cross, LG15: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG15$cM, gdaysM_LG15$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG15$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG15$cM, gdaysM_LG15$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG15$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG16$cM, gdaysM_LG16$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG16$cM)), ylab="days", xlab="cM", main="G cross, LG16: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG16$cM, gdaysM_LG16$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG16$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG16$cM, gdaysM_LG16$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG16$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

###LG 17: 19
layout(matrix(c(1,2,3,4,5,6),2,3,byrow=TRUE), heights=c(1,2))
plot(gdaysM_LG17$cM, gdaysM_LG17$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG17", xlim=c(0,max(gdaysM_LG17$cM)))
plot(gdaysM_LG18$cM, gdaysM_LG18$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG18", xlim=c(0,max(gdaysM_LG18$cM)))
plot(gdaysM_LG19$cM, gdaysM_LG19$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG19", xlim=c(0,max(gdaysM_LG19$cM)))

plot(gdaysM_LG17$cM, gdaysM_LG17$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG17$cM)), ylab="days", xlab="cM", main="G cross, LG17: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG17$cM, gdaysM_LG17$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG17$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG17$cM, gdaysM_LG17$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG17$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG18$cM, gdaysM_LG18$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG18$cM)), ylab="days", xlab="cM", main="G cross, LG18: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG18$cM, gdaysM_LG18$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG18$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG18$cM, gdaysM_LG18$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG18$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysM_LG19$cM, gdaysM_LG19$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysM_LG19$cM)), ylab="days", xlab="cM", main="G cross, LG19: Surv by Gen")
par(new=TRUE)
plot(gdaysM_LG19$cM, gdaysM_LG19$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysM_LG19$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysM_LG19$cM, gdaysM_LG19$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysM_LG19$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")


################BELOW WILL FOLLOW THE SAME ANALYSIS AS ABOVE, FOR GDAYSF#######################

gdaysF_LG1 <- subset(gdaysF, gdaysF$LG == '1')
gdaysF_LG2 <- subset(gdaysF, gdaysF$LG == '2')
gdaysF_LG3 <- subset(gdaysF, gdaysF$LG == '3')
gdaysF_LG4 <- subset(gdaysF, gdaysF$LG == '4')
gdaysF_LG5 <- subset(gdaysF, gdaysF$LG == '5')
gdaysF_LG6 <- subset(gdaysF, gdaysF$LG == '6')
gdaysF_LG7 <- subset(gdaysF, gdaysF$LG == '7')
gdaysF_LG8 <- subset(gdaysF, gdaysF$LG == '8')
gdaysF_LG9 <- subset(gdaysF, gdaysF$LG == '9')
gdaysF_LG10 <- subset(gdaysF, gdaysF$LG == '10')
gdaysF_LG11 <- subset(gdaysF, gdaysF$LG == '11')
gdaysF_LG12 <- subset(gdaysF, gdaysF$LG == '12')
gdaysF_LG13 <- subset(gdaysF, gdaysF$LG == '13')
gdaysF_LG14 <- subset(gdaysF, gdaysF$LG == '14')
gdaysF_LG15 <- subset(gdaysF, gdaysF$LG == '15')
gdaysF_LG16 <- subset(gdaysF, gdaysF$LG == '16')
gdaysF_LG17 <- subset(gdaysF, gdaysF$LG == '17')
gdaysF_LG18 <- subset(gdaysF, gdaysF$LG == '18')
gdaysF_LG19 <- subset(gdaysF, gdaysF$LG == '19')

### LG 1:4
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysF_LG1$cM, gdaysF_LG1$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,50.0),  main="G cross, LG1", xlim=c(0,max(gdaysF_LG1$cM)))
plot(gdaysF_LG2$cM, gdaysF_LG2$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG2", xlim=c(0,max(gdaysF_LG2$cM)))
plot(gdaysF_LG3$cM, gdaysF_LG3$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG3", xlim=c(0,max(gdaysF_LG3$cM)))
plot(gdaysF_LG4$cM, gdaysF_LG4$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG4", xlim=c(0,max(gdaysF_LG4$cM)))

plot(gdaysF_LG1$cM, gdaysF_LG1$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG1$cM)), ylab="days", xlab="cM", main="G cross, LG1: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG1$cM, gdaysF_LG1$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG1$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG1$cM, gdaysF_LG1$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG1$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG2$cM, gdaysF_LG2$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG2$cM)), ylab="days", xlab="cM", main="G cross, LG2: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG2$cM, gdaysF_LG2$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG2$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG2$cM, gdaysF_LG2$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG2$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG3$cM, gdaysF_LG3$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG3$cM)), ylab="days", xlab="cM", main="G cross, LG3: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG3$cM, gdaysF_LG3$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG3$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG3$cM, gdaysF_LG3$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG3$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG4$cM, gdaysF_LG4$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG4$cM)), ylab="days", xlab="cM", main="G cross, LG4: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG4$cM, gdaysF_LG4$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG4$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG4$cM, gdaysF_LG4$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG4$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

### LG 5:8
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysF_LG5$cM, gdaysF_LG5$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG5", xlim=c(0,max(gdaysF_LG5$cM)))
plot(gdaysF_LG6$cM, gdaysF_LG6$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG6", xlim=c(0,max(gdaysF_LG6$cM)))
plot(gdaysF_LG7$cM, gdaysF_LG7$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG7", xlim=c(0,max(gdaysF_LG7$cM)))
plot(gdaysF_LG8$cM, gdaysF_LG8$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG8", xlim=c(0,max(gdaysF_LG8$cM)))

plot(gdaysF_LG5$cM, gdaysF_LG5$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG5$cM)), ylab="days", xlab="cM", main="G cross, LG5: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG5$cM, gdaysF_LG5$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG5$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG5$cM, gdaysF_LG5$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG5$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG6$cM, gdaysF_LG6$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG6$cM)), ylab="days", xlab="cM", main="G cross, LG6: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG6$cM, gdaysF_LG6$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG6$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG6$cM, gdaysF_LG6$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG6$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG7$cM, gdaysF_LG7$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG7$cM)), ylab="days", xlab="cM", main="G cross, LG7: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG7$cM, gdaysF_LG7$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG7$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG7$cM, gdaysF_LG7$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG7$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG8$cM, gdaysF_LG8$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG8$cM)), ylab="days", xlab="cM", main="G cross, LG8: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG8$cM, gdaysF_LG8$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG8$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG8$cM, gdaysF_LG8$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG8$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")


### LG 9:12
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysF_LG9$cM, gdaysF_LG9$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG9", xlim=c(0,max(gdaysF_LG9$cM)))
plot(gdaysF_LG10$cM, gdaysF_LG10$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG10", xlim=c(0,max(gdaysF_LG10$cM)))
plot(gdaysF_LG11$cM, gdaysF_LG11$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG11", xlim=c(0,max(gdaysF_LG11$cM)))
plot(gdaysF_LG12$cM, gdaysF_LG12$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG12", xlim=c(0,max(gdaysF_LG12$cM)))

plot(gdaysF_LG9$cM, gdaysF_LG9$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG9$cM)), ylab="days", xlab="cM", main="G cross, LG9: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG9$cM, gdaysF_LG9$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG9$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG9$cM, gdaysF_LG9$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG9$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG10$cM, gdaysF_LG10$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG10$cM)), ylab="days", xlab="cM", main="G cross, LG10: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG10$cM, gdaysF_LG10$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG10$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG10$cM, gdaysF_LG10$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG10$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG11$cM, gdaysF_LG11$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG11$cM)), ylab="days", xlab="cM", main="G cross, LG11: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG11$cM, gdaysF_LG11$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG11$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG11$cM, gdaysF_LG11$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG11$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG12$cM, gdaysF_LG12$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG12$cM)), ylab="days", xlab="cM", main="G cross, LG12: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG12$cM, gdaysF_LG12$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG12$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG12$cM, gdaysF_LG12$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG12$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

###LG 13 to 16
layout(matrix(c(1,2,3,4,5,6,7,8),2,4,byrow=TRUE), heights=c(1,2))
plot(gdaysF_LG13$cM, gdaysF_LG13$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG13", xlim=c(0,max(gdaysF_LG13$cM)))
plot(gdaysF_LG14$cM, gdaysF_LG14$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG14", xlim=c(0,max(gdaysF_LG14$cM)))
plot(gdaysF_LG15$cM, gdaysF_LG15$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG15", xlim=c(0,max(gdaysF_LG15$cM)))
plot(gdaysF_LG16$cM, gdaysF_LG16$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG16", xlim=c(0,max(gdaysF_LG16$cM)))

plot(gdaysF_LG13$cM, gdaysF_LG13$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG13$cM)), ylab="days", xlab="cM", main="G cross, LG13: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG13$cM, gdaysF_LG13$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG13$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG13$cM, gdaysF_LG13$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG13$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG14$cM, gdaysF_LG14$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG14$cM)), ylab="days", xlab="cM", main="G cross, LG14: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG14$cM, gdaysF_LG14$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG14$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG14$cM, gdaysF_LG14$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG14$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG15$cM, gdaysF_LG15$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG15$cM)), ylab="days", xlab="cM", main="G cross, LG15: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG15$cM, gdaysF_LG15$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG15$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG15$cM, gdaysF_LG15$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG15$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG16$cM, gdaysF_LG16$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG16$cM)), ylab="days", xlab="cM", main="G cross, LG16: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG16$cM, gdaysF_LG16$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG16$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG16$cM, gdaysF_LG16$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG16$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

###LG 17: 19
layout(matrix(c(1,2,3,4,5,6),2,3,byrow=TRUE), heights=c(1,2))
plot(gdaysF_LG17$cM, gdaysF_LG17$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG17", xlim=c(0,max(gdaysF_LG17$cM)))
plot(gdaysF_LG18$cM, gdaysF_LG18$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG18", xlim=c(0,max(gdaysF_LG18$cM)))
plot(gdaysF_LG19$cM, gdaysF_LG19$neg_log.qval., col="orange", lwd=3, ylab="-log(qval)", xlab="cM", ylim=c(0,3.0),  main="G cross, LG19", xlim=c(0,max(gdaysF_LG19$cM)))

plot(gdaysF_LG17$cM, gdaysF_LG17$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG17$cM)), ylab="days", xlab="cM", main="G cross, LG17: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG17$cM, gdaysF_LG17$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG17$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG17$cM, gdaysF_LG17$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG17$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG18$cM, gdaysF_LG18$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG18$cM)), ylab="days", xlab="cM", main="G cross, LG18: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG18$cM, gdaysF_LG18$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG18$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG18$cM, gdaysF_LG18$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG18$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")

plot(gdaysF_LG19$cM, gdaysF_LG19$med0, col="red", ylim=c(180,380), xlim=c(0,max(gdaysF_LG19$cM)), ylab="days", xlab="cM", main="G cross, LG19: Surv by Gen")
par(new=TRUE)
plot(gdaysF_LG19$cM, gdaysF_LG19$med1, col="black", ylim=c(180,380), xlim=c(0,max(gdaysF_LG19$cM)), ylab="", xlab="")
par(new=TRUE)
plot(gdaysF_LG19$cM, gdaysF_LG19$med2, col="blue", ylim=c(180,380), xlim=c(0,max(gdaysF_LG19$cM)), ylab="", xlab="")
legend(10,380,  c("SL/SL", "SL/LL", "LL/LL"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("red","black", "blue"), bty="n")


